### ISSUE TITLE
Documentation Feedback

### ISSUE THREAD

**Issue by robin-fhnw** [robin-fhnw/IP5-Puerro#12]
Would it be possible for you to give us feedback on the current state of our [documentation](https://github.com/robin-fhnw/IP5-Puerro/tree/master/docs)?

Maybe we could also arrange a meeting for next Tuesday.
Do you have time at 10:00 o'clock in the 'Programmierzentrum'?

Thank you :)

**Comment by Dierk** [comment]
I like it very much!
Small suggestions for improvement:
* put a link at the end of each chapter that links to the next chapter for easier reading
* have a look at either github.io (github pages) or even gitbooks, which would produce a proper online book plus pdf and e-reader formats from the same source.

**Comment by gobeli** [comment]
Thank you for the feedback and suggestions @Dierk

Are you and @DieterHolz available for a meeting tomorrow at 10AM?

**Comment by Dierk** [comment]
me: yes. I've sent you an invitation but my calendar might have swallowed it...
