### ISSUE TITLE
As a user, I want to receive feedback on the input I am currently making

### ISSUE THREAD

**Issue by robin-fhnw** [robin-fhnw/IP5-Puerro#3]
### Problem
I don't know if the input I'm currently making is correct or makes sense.

### Usage Examples
- Notification about errors during form submission
- Notification that the input is correct
- Feedback on current input field (e.g. password strength)

### Implementation Ideas
- Data Binding with a Framework (Angular, Vue, React)
- JavaScript Event Listeners
- ES7 Observable
- Own implementation of Observable
- HTML5 Input Validation
- ...

**Comment by gobeli** [comment]
A possible solution is a combination of HTML5 validation with vanilla JS: https://stackblitz.com/edit/js-cuojtu.
